### ISSUE TITLE
`Not found` at link for learn/natural-language-processing

### ISSUE THREAD

**Issue by 2cb-log** [P1xt/speedstudy#25]
There are of course other related courses but looks like some site reorganization at Coursera makes this link miss:  [Introduction to Natural Language Processing](https://www.coursera.org/learn/natural-language-processing)

There is a course with a very similar title from National Research University Higher School of Economics but it's part of a "specialization" program which makes me think it's not the original.

**Comment by P1xt** [comment]
You're right, the course course you get from search isn't the same one. The original was from University of Michigan and it doesn't appear to be available on Coursera any more. I can find the videos on YouTube but they'd likely be less useful without exams, etc.

I'll find a suitable alternative for that spot in the curriculum. Are you up to that point now (needing an alternative sooner rather than later), if so, I'll try to light a fire under my research. If not, I'll probably take a week or two to weigh all the options.

**Comment by 2cb-log** [comment]
Please do NOT light a fire on my account!  😄   I was just doing a quick peek-ahead as in loosely laying out what my personalized long-term / "to completion" roadmap might look like.

Thanks as always for keeping these current, especially given the continual morphing of the MOOC landscape.

**Comment by P1xt** [comment]
It's a never ending "update" process - usually not too bad through, there's typically a reasonable alternative. This one's a bit tougher though, the original was quite good, finding a replacement might mean I end up picking an equally good alternative from a different topic. (Natural Language Processing was included as part of my intention to include a "breadth" of topics.)

**Comment by P1xt** [comment]
After much searching for a suitable replacement in the same topic, I opted for substituting with a similarly rigorous introduction in a different topic (Robotics). There really just wasn't a good NLP replacement available.
